Fix app crashes when touching bomb by passing correct type to `camera.shake()`
TLDR; 
* App crashes when touching a bomb with error.
    * `AttributeError: 'tuple' object has no attribute 'x'`
* Made the following changes
    * added `from pyglet.math import Vec2` to the top of the file
    * passed `Vec2` to `camera.shake()` instead of tuple
        * old line: `camera.shake((4, 7))`
        * new line: `camera.shake(Vec2(4, 7))`

I initially thought this was intended behavior but I realized the app was actually just crashing.

The offending line was calling `camera.shake()` which according to it's definition in `./venv/lib/python3.11/site-packages/arcade/camera.py` expects a `Vec2` as it's argument which is being imported in that file with `from pyglet.math import Mat4, Vec2, Vec3` but the call to `camera.shake` was getting a `tuple` hence the `AttributeError`.